import { Component, signal } from '@angular/core';

const PREMIUM_EXAMPLES = [
  { id:'worker-processing', label:'Large data', title:'Worker-powered processing', description:'Keep 100,000 or 1,000,000 rows in a dedicated module worker while the table receives bounded pages and the interface stays responsive.', image:'premium/worker-processing.webp', alt:'Large WTS Data Table dataset processed through a dedicated worker', caption:'Worker processing · bounded table pages', code:`import { createWorkerProcessingClient } from 'wts-data-table/worker-client';\nimport { createBrowserWorkerTransport } from 'wts-data-table/worker-browser';\nimport { createWorkerTableController } from 'wts-data-table/worker-table';\n\nconst license = await verifyDataTableLicense(entitlementToken);\nconst client = createWorkerProcessingClient({\n  license,\n  createTransport: () => createBrowserWorkerTransport(\n    new URL('./worker.js', import.meta.url), { license }\n  )\n});\nawait client.loadSnapshot(snapshot);\nconst bridge = createWorkerTableController({\n  license, client, blockSize: 100, maxBlocks: 3,\n  ...tableAdapter\n});\nawait bridge.refresh();` },
  { id:'remote-viewport', label:'Server data', title:'Remote data viewport', description:'Request only visible blocks from an application-owned source while retaining a bounded row window, selection state, and native table interaction.', image:'premium/remote-viewport.webp', alt:'Bounded WTS Data Table viewport backed by a remote dataset', caption:'Remote viewport · application-owned source', code:`import { createRemoteViewportController } from 'wts-data-table/remote-viewport';\nimport { createRemoteRowModel } from 'wts-data-table/remote';\n\nconst model = createRemoteRowModel({\n  license, source, blockSize: 50, maxBlocks: 3\n});\nconst remote = createRemoteViewportController({\n  license, model, rowHeight: 60, maxWindowRows: 1000,\n  getState: () => table.getState(),\n  subscribe: listener => table.core.subscribe(listener),\n  setRowWindow: (window, options) => table.setRowWindow(window, options),\n  getViewportRange: () => table.getViewportRange(),\n  scrollToRow: index => table.scrollToRow(index)\n});\nawait remote.refresh();` },
  { id:'formula-editor', label:'Spreadsheet logic', title:'Formula workbook and editor', description:'Keep canonical formulas stable while the table is sorted, filtered, or reordered, with an explicit formula bar and atomic commits.', image:'premium/formula-editor.webp', alt:'Formula editor connected to calculated WTS Data Table cells', caption:'Formula workbook · atomic editor commits', code:`import { createFormulaWorkbook } from 'wts-data-table/formula-engine';\nimport { createFormulaTableBridge } from 'wts-data-table/formula-table';\nimport { createFormulaEditor } from 'wts-data-table/formula-editor';\n\nconst workbook = createFormulaWorkbook({\n  license, rowIds, columnIds\n});\nconst bridge = createFormulaTableBridge({\n  license, workbook, table\n});\nconst editor = createFormulaEditor({\n  license, container: formulaHost, bridge\n});` },
] as const;

@Component({
  template: `
    <section class="page-hero wrap"><span class="kicker">Advanced capabilities</span><h1>Complex data.<br><em>Production workflows.</em></h1><p>Explore licensed capabilities for large-scale processing, remote datasets, and spreadsheet logic. Each example pairs a working product view with the package APIs used to implement it.</p></section>
    <section class="premium-list wrap">@for(item of examples;track item.id){<article><div class="premium-copy"><span class="kicker">{{ item.label }}</span><h2>{{ item.title }}</h2><p>{{ item.description }}</p><div class="code-block"><div><span>TypeScript</span><button type="button" (click)="copy(item.code,item.id)">{{ copied()===item.id?'Copied':'Copy code' }}</button></div><pre><code>{{ item.code }}</code></pre></div></div><figure><img [src]="item.image" [alt]="item.alt" width="1440" height="900" loading="lazy"><figcaption>{{ item.caption }}</figcaption></figure></article>}</section>
    <section class="premium-boundary wrap"><strong>Package and entitlement</strong><p>These capabilities are included in <code>wts-data-table</code> 1.0.2 and later under feature-named imports. Advanced factories require a verified signed entitlement; developers install one package and use the same table API.</p></section>
  `,
  styles: [`
    .premium-list{display:grid;gap:7rem}.premium-list article{display:grid;grid-template-columns:minmax(320px,.72fr) minmax(0,1.28fr);gap:4rem;align-items:center}.premium-list article:nth-child(even){grid-template-columns:minmax(0,1.28fr) minmax(320px,.72fr)}.premium-list article:nth-child(even) .premium-copy{order:2}.premium-list h2{margin:.7rem 0 1rem;font-size:clamp(2.2rem,4vw,4rem);letter-spacing:-.06em}.premium-copy>p{color:var(--muted);line-height:1.75}.premium-list figure{margin:0;overflow:hidden;border:1px solid var(--line);border-radius:12px;background:white;box-shadow:0 28px 70px rgba(24,35,52,.13)}.premium-list img{display:block;width:100%;height:auto}.premium-list figcaption{padding:.7rem 1rem;background:white;color:var(--muted);font:.65rem var(--mono);text-transform:uppercase}.code-block{margin-top:1.5rem;overflow:hidden;border-radius:10px;background:#121a28;color:#d7e0ee}.code-block>div{display:flex;justify-content:space-between;padding:.7rem .9rem;border-bottom:1px solid #2e394a;color:#8ea0b8;font:.65rem var(--mono)}.code-block button{border:0;background:transparent;color:var(--lime);cursor:pointer}.code-block pre{max-height:280px;margin:0;padding:1rem;overflow:auto;font:.7rem/1.65 var(--mono)}.premium-boundary{margin-top:5rem;padding:1.2rem;border:1px solid #e6d19f;border-radius:10px;background:#fff8e6}.premium-boundary p{margin:.45rem 0 0;color:var(--muted);line-height:1.65}
    @media(max-width:900px){.premium-list article,.premium-list article:nth-child(even){grid-template-columns:1fr;gap:2rem}.premium-list article:nth-child(even) .premium-copy{order:0}}
  `],
})
export class PremiumPage { protected readonly examples=PREMIUM_EXAMPLES; protected readonly copied=signal(''); protected async copy(code:string,id:string){await navigator.clipboard.writeText(code);this.copied.set(id);window.setTimeout(()=>this.copied.set(''),1400)} }
